# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=1000)),
                ('pypi_url', models.CharField(max_length=400)),
                ('current_version', models.CharField(max_length=100)),
                ('downloads_count', models.IntegerField()),
            ],
        ),
    ]
